### ISSUE TITLE
The last message is resent if you refresh the page

### ISSUE THREAD

**Issue by TheCoolerSuptelov** [ltpitt/java-spring-thymeleaf-chat#2]
The last message is resent if you refresh the page. 

Before reloading
![image](https://user-images.githubusercontent.com/102233851/163678315-bc136d78-afcf-405b-a933-ec8e47c86830.png)

After 
![image](https://user-images.githubusercontent.com/102233851/163678305-3e9a7150-c19b-4e85-93b0-acd0b56d650a.png)

**Comment by ltpitt** [comment]
Thanks for the fix!
